plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.1'
    id 'xyz.jpenilla.run-paper' version '3.1.0'
}

group = 'su.nezushin'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.3.build.+")
    implementation("net.bytebuddy:byte-buddy:1.18.14")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.4")
}

tasks {
    test {
        useJUnitPlatform()
    }
    runServer {
        minecraftVersion("26.3")
    }
    shadowJar {
        archiveClassifier.set("")
        relocate("net.bytebuddy", "su.nezushin.fr.lib.bytebuddy")
    }
    jar {
        archiveClassifier.set("thin")
    }
    build {
        dependsOn tasks.shadowJar
    }
}

def targetJavaVersion = 25
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
